import type { Metadata } from "next";
import SideBar from "@/components/SideBar";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "MovieBox",
  description: "Generated by create next app",
};

export default function DescriptionLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={`${poppins.className} min-h-screen flex`}>
      <SideBar />

      <main className="relative flex-1 h-full">{children}</main>
    </div>
  );
}
